# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Trajectory Controllers ---------------------------------------
#
# Effort Position Controllers ---------------------------------------
effort_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    # VALUES ARE NOT CORRECT !
  gains:
    iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30}
    iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
    iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
    iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
    iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
    iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
    iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default

gripper_left_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_left_joint
  pid: {p: 10.0, i: 0.0, d: 0.1, i_clamp_min: -1, i_clamp_max: 1}

gripper_right_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_right_joint
  pid: {p: 10.0, i: 0.0, d: 0.1, i_clamp_min: -1, i_clamp_max: 1}
