# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Trajectory Controllers ---------------------------------------
#
# Effort Position Controllers ---------------------------------------
effort_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    # VALUES ARE NOT CORRECT !
  gains:
    iiwa_joint_1: {p: 3000,  d: 2, i: 1, i_clamp: 1}
    iiwa_joint_2: {p: 2000,  d: 2, i: 1, i_clamp: 1}
    iiwa_joint_3: {p: 1000,  d: 2, i: 1, i_clamp: 1}
    iiwa_joint_4: {p: 1000,  d: 2, i: 1, i_clamp: 1}
    iiwa_joint_5: {p: 1000,  d: 2, i: 1, i_clamp: 1}
    iiwa_joint_6: {p: 1000,  d: 2, i: 1, i_clamp: 1}
    iiwa_joint_7: {p: 1000,  d: 2, i: 1, i_clamp: 1}

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default

gripper_left_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_left_joint
  pid: {p: 3000.0, i: 1, d: 2, i_clamp_min: -1, i_clamp_max: 1}

gripper_right_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_right_joint
  pid: {p: 1000.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}

effort_j1_position_controller:
  type: effort_controllers/JointPositionController
  joint: iiwa_joint_1
  pid: {p: 3000,  d: 2, i: 1, i_clamp: 1}

effort_j2_position_controller:
  type: effort_controllers/JointPositionController
  joint: iiwa_joint_2
  pid: {p: 2000,  d: 2, i: 1, i_clamp: 1}

effort_j3_position_controller:
  type: effort_controllers/JointPositionController
  joint: iiwa_joint_3
  pid: {p: 1000,  d: 2, i: 1, i_clamp: 1}

effort_j4_position_controller:
  type: effort_controllers/JointPositionController
  joint: iiwa_joint_4
  pid: {p: 1000,  d: 2, i: 1, i_clamp: 1}

effort_j5_position_controller:
  type: effort_controllers/JointPositionController
  joint: iiwa_joint_5
  pid: {p: 1000,  d: 2, i: 1, i_clamp: 1}

effort_j6_position_controller:
  type: effort_controllers/JointPositionController
  joint: iiwa_joint_6
  pid: {p: 1000,  d: 2, i: 1, i_clamp: 1}

effort_j7_position_controller:
  type: effort_controllers/JointPositionController
  joint: iiwa_joint_7
  pid: {p: 1000,  d: 2, i: 1, i_clamp: 1}
